# Generated by Django 6.0.3 on 2026-03-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('CAD', 'CAD — Canadian Dollar'), ('AUD', 'AUD — Australian Dollar'), ('NGN', 'NGN — Nigerian Naira'), ('GHS', 'GHS — Ghanaian Cedi'), ('KES', 'KES — Kenyan Shilling'), ('ZAR', 'ZAR — South African Rand')], default='USD', max_length=3),
        ),
    ]
