# Generated by Django 6.0.3 on 2026-03-03 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verification_code', models.CharField(blank=True, max_length=128, null=True)),
                ('pending_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_email_change', models.DateTimeField(blank=True, null=True)),
                ('resend_count', models.IntegerField(default=0)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
