# Generated by Django 6.0.3 on 2026-03-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_username_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verify_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
