# Generated by Django 6.0.3 on 2026-03-06 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0004_blueprintmessage_uuid'),
        ('organizations', '0003_membership_uuid'),
        ('projects', '0003_project_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blueprint',
            index=models.Index(fields=['organization', 'is_complete'], name='blueprint_org_complete_idx'),
        ),
    ]
